apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-app
          image: server-app:0.5
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "3000"
