apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      volumes:
      - name: ping-pv
        persistentVolumeClaim:
          claimName: ping-volume-claim
      containers:
        - name: server-app
          image: server-app:0.16
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "3000"
          volumeMounts:
          - name: ping-pv
            mountPath: /usr/src/app/shared

