# for string and server app, ex. 1.10

apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: reader-app
          image: reader-app:0.7
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/shared
        - name: generator-app
          image: generator-app:0.5
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/shared
