apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-app
  template:
    metadata:
      labels:
        app: logoutput-app
    spec:
      volumes:
      - name: ping-pv
        persistentVolumeClaim:
          claimName: ping-volume-claim
      containers:
        - name: logoutput-app
          image: log-output-app:16
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "3000"
          volumeMounts:
          - name: ping-pv
            mountPath: /usr/src/app/shared
